### ISSUE TITLE
Cannot reproduce the example in Readme main page

### ISSUE THREAD

**Issue by tifDev** [DeDolphins/DataHorse#3]
Hi,

I was giving a try to this project by testing the sample provided first.
However, Im stuck on below error, can you please help?

```
>>> import datahorse
>>> 
>>> df = datahorse.read('https://raw.githubusercontent.com/plotly/datasets/master/iris-data.csv')
>>> df = df.chat('convert species names to numeric codes')
Traceback (most recent call last):
  File "/home/xxx/.pyenv/versions/3.10.14/envs/data_science/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xxx/.pyenv/versions/3.10.14/envs/data_science/lib/python3.10/site-packages/datahorse/core.py", line 127, in __call__
    return ask(goal, data, *args)
  File "/home/xxx/.pyenv/versions/3.10.14/envs/data_science/lib/python3.10/site-packages/datahorse/core.py", line 101, in __call__
    return self._eval(source, *args)
  File "/home/xxx/.pyenv/versions/3.10.14/envs/data_science/lib/python3.10/site-packages/datahorse/core.py", line 79, in _eval
    exec(self._fill_template('''
  File "<string>", line 15, in <module>
  File "<string>", line 12, in process
  File "/home/xxx/.pyenv/versions/3.10.14/envs/data_science/lib/python3.10/site-packages/pandas/core/frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/xxx/.pyenv/versions/3.10.14/envs/data_science/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 0
>>> df['species'] = df['species'].astype('category').cat.codes
Traceback (most recent call last):
  File "/home/xxx/.pyenv/versions/3.10.14/envs/data_science/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'species'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xxx/.pyenv/versions/3.10.14/envs/data_science/lib/python3.10/site-packages/pandas/core/frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/xxx/.pyenv/versions/3.10.14/envs/data_science/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'species'
>>> print(df.columns)
Index(['sepal length', 'sepal width', 'petal length', 'petal width', 'class'], dtype='object')
>>> print(df.head())
   sepal length  sepal width  petal length  petal width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

```

Thanks

**Comment by SsebowaDisan** [comment]
Hi,

Thank you for reaching out! It looks like the column name in your dataset is class rather than species. You can update your code to use the correct column name. Here’s how you can modify it:

df = df.chat('convert class names to numeric codes')

Or

df = df.chat('convert class names to numeric data')

This should resolve the KeyError you're encountering and we remain at your disposal for any questions or challenges.

We will also update the README to reflect this change to avoid confusion in the future. 

Thanks for pointing this out!

**Comment by anandpotukuchi** [comment]
Is this resolved?

**Comment by SsebowaDisan** [comment]
Yes the issue was solved 
![Image 25-08-2024 at 08 35](https://github.com/user-attachments/assets/c9078123-19a5-43e8-b6b9-1e7b37d72bed)
